table agriculture-sylviculture-et-peche-valeur-ajoutee-du-pib-
	lineageTag: 03146d6a-5354-41c4-8a67-ba473287e123

	column indicator
		dataType: string
		lineageTag: 9a8bcef1-4c35-4630-a6cf-429850971c28
		summarizeBy: none
		sourceColumn: indicator

		annotation SummarizationSetBy = Automatic

	column date
		dataType: int64
		formatString: 0
		lineageTag: 56f9230a-18bf-424b-aa0c-fd0e32b1b830
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column value
		dataType: double
		lineageTag: 488f323b-b7af-4c28-8d7a-ac4e978cea1f
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column unit
		dataType: string
		lineageTag: ccfbd44b-f3b5-4f00-9728-0156d56847a4
		summarizeBy: none
		sourceColumn: unit

		annotation SummarizationSetBy = Automatic

	column obs_status
		dataType: string
		lineageTag: 26aac6af-a585-40b5-850d-9793d7dcb03d
		summarizeBy: none
		sourceColumn: obs_status

		annotation SummarizationSetBy = Automatic

	column decimal
		dataType: int64
		formatString: 0
		lineageTag: 377809cc-2d2e-463f-a99a-28d6a0ad5871
		summarizeBy: sum
		sourceColumn: decimal

		annotation SummarizationSetBy = Automatic

	column Code_pays
		dataType: string
		lineageTag: 932ace68-82fa-43a2-98eb-853d118343ac
		summarizeBy: none
		sourceColumn: Code_pays

		annotation SummarizationSetBy = Automatic

	partition agriculture-sylviculture-et-peche-valeur-ajoutee-du-pib- = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\MJ\MJ_consulting\Data community Togo\sept_joursC\agriculture-sylviculture-et-peche-valeur-ajoutee-du-pib-.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"indicator", type text}, {"country", type text}, {"countryiso3code", type text}, {"date", Int64.Type}, {"value", type text}, {"unit", type text}, {"obs_status", type text}, {"decimal", Int64.Type}}),
				    #"Colonnes supprimées" = Table.RemoveColumns(#"Type modifié",{"country", "countryiso3code"}),
				    #"Valeur remplacée" = Table.ReplaceValue(#"Colonnes supprimées",".",",",Replacer.ReplaceText,{"value"}),
				    #"Type modifié1" = Table.TransformColumnTypes(#"Valeur remplacée",{{"value", type number}}),
				    #"Duplication de la colonne" = Table.DuplicateColumn(#"Type modifié1", "obs_status", "obs_status - Copier"),
				    #"Colonnes renommées" = Table.RenameColumns(#"Duplication de la colonne",{{"obs_status - Copier", "Code_pays"}}),
				    #"Valeur remplacée1" = Table.ReplaceValue(#"Colonnes renommées","","TGO",Replacer.ReplaceValue,{"Code_pays"})
				in
				    #"Valeur remplacée1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

